"""
Django settings for rule2 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sb7o32fie-ce$8b%gg=w+%*&yx1ii7-khwyi+e_dt5rd8-2^3o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# TEMPLATE_DEBUG = True
TEMPLATE_DEBUG = DEBUG

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'mod_wsgi.server',
    'rules_app',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'rule2.urls'

WSGI_APPLICATION = 'rule2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        # 'NAME': 'db_sanqiang',
        # 'USER': 'data',
        # 'PASSWORD': 'data2123',
        # 'HOST': '192.168.1.90',
        # 'PORT': '3306',

        # 'NAME': 'db_jiuyang',
        # 'USER': 'kettle',
        # 'PASSWORD': 'kettle2015',
        # 'HOST': 'www.e-corp.cn',
        # 'PORT': '3306',

        'NAME': 'db_jiuyang',
        'USER': 'zczx_data',
        'PASSWORD': 'cos2x=2Sinxcosx',
        'HOST': 'www.e-corp.cn',
        'PORT': '3306',

        # 'NAME': 'db_jiuyang',
        # 'USER': 'kettle',
        # 'PASSWORD': 'root',
        # 'HOST': '192.168.1.110',
        # 'PORT': '33060',

        # 'NAME': 'db_jiuyang',
        # 'USER': 'rulesys',
        # 'PASSWORD': 'rulesys2015',
        # 'HOST': '127.0.0.1',
        # 'PORT': '3306',
    },
    'JY': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_jiuyang',
        'USER': 'kettle',
        'PASSWORD': 'root',
        'HOST': '192.168.1.110',
        'PORT': '33060',
    }
}

# DATABASE_ROUTERS = ['new_ecgoo.dbrouter.MyAppRouter', 'new_ecgoo.dbrouter.MasterSlaveRouter']

# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

# TEMPLATE_DIRS = (
#     # Put strings here, like "/home/html/django_templates".
#     # Always use forward slashes, even on Windows.
#     'E:/workspace/rule2/rules_app/templates',
# )
# STATIC_PATH = 'E:/workspace/rule2/rules_app/static'
